DROP TABLE IF EXISTS CONTO_TRANSACTION;

CREATE TABLE CONTO_TRANSACTION (
      TRANSACTION_ID VARCHAR(100) PRIMARY KEY,
      OPERATION_ID VARCHAR(100),
      ACCOUNTING_DATE DATE,
      VALUE_DATE DATE,
      TYPE_ENUMERATION VARCHAR(50),
      TYPE_VALUE VARCHAR(50),
      AMOUNT DOUBLE NOT NULL,
      CURRENCY VARCHAR(3),
      DESCRIPTION VARCHAR(500)
  )
